name: Push submodule update dispatch event to droidboot_gui repo
on: [ push, workflow_dispatch ]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Notify droidboot_gui repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: "Android-Boot-Manager/droidboot_gui"
          event-type: update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "module": "Android-Boot-Manager/droidboot_platforms", "branch": "main"}'
